- name: play3
  gather_facts: True
  hosts: web-server
  vars_files: ./variables.yml

  tasks:
    - name: Install nginx
      apt:
        name: "{{item.package_name}}"
        state: "{{item.package_state}}"
      loop: "{{ packages }}"
      when: ansible_facts['distribution'] == "Ubuntu"
      register: x

    - name: depuggin
      debug:
        msg: "{{x}}"


    - name: ping 
      ping:
      when: x.msg == "All items completed"

    - name: restart service
      sysvinit:
        name: nginx
        state: restarted
      when: x.changed == false





    


