- name: play2
  gather_facts: True
  hosts: web-server
  vars_files: ./variables.yml

  tasks:
    - name: Install nginx
      apt:
        name: "{{item.package_name}}"
        state: "{{item.package_state}}"
      loop: "{{ packages }}"

    - name: restart nginx web-server
      sysvinit: 
        name: nginx
        state: restarted
        enabled: yes
      when: ansible_facts['distribution'] == "Ubuntu" 
    
    - name: restart if 'distribution' is httpd
      sysvinit:
        name: httpd
        state: restarted
      when: ansible_facts['distribution'] == "CentOS"


