- name: play1 
  gather_facts: false
  hosts: all
  vars:
    package_name: nginx
    package_state: latest
  tasks:

    - name:  install ngnix servre
      tags: install
      apt:
          name: "{{package_name}}"
          state: "{{package_state}}"